### ISSUE TITLE
Duplicated tx when transfering ownership

### ISSUE THREAD

**Issue by Siegrift** [vacuumlabs/name-bazaar#39]
1. Register domain
2. Create buy now offering
3. Transfer ownership to it

The transaction log will have two entries for the transfer (which means there are porbably 2 txs)
![twice](https://user-images.githubusercontent.com/22679154/108072266-fa1b4b80-7066-11eb-8309-fdba410b7197.png)

**Comment by ladislavdubravsky** [comment]
This is intended, but should have more user friendly presentation.

https://github.com/vacuumlabs/name-bazaar/pull/20#discussion_r569606616

**Comment by Siegrift** [comment]
This was fixed by https://github.com/vacuumlabs/name-bazaar/pull/40
