### ISSUE TITLE
Emergency cancel when reclaiming ownership

### ISSUE THREAD

**Issue by Siegrift** [vacuumlabs/name-bazaar#41]
Steps to repro:
1. Create offering
2. Click `Show` in the notification panel
3. Transfer ownership
4. Reclaim

Why we have emergency cancel? There doesn't seem to be any error in FE nor BE.

**Comment by ladislavdubravsky** [comment]
There is no problem here. Emergency multisig address is supposed to be able to cancel anyone's offering ([see here](https://github.com/vacuumlabs/name-bazaar/blob/master/resources/public/contracts/src/Offering.sol#L133)) and just so it happens that the first ganache account is chosen as the emergeny multisig in dev deploy ([see here](https://github.com/vacuumlabs/name-bazaar/blob/master/src/name_bazaar/server/deployer.cljs#L93)).

The point to take from this is, unless we're testing emergency multisig functionality, we should use 2nd and later ganache accounts.

**Comment by Siegrift** [comment]
Good to know! I think we can close this then.
