### ISSUE TITLE
Page not found when clicking on offering in notifications

### ISSUE THREAD

**Issue by Siegrift** [vacuumlabs/name-bazaar#42]
1. Create offering (e,g. `rgrg.eth`)
2. Click the entry in notification panel
3. You will be redirected to `http://localhost:4544/name/rgrg.eth`, which doesn't exist

**Comment by ladislavdubravsky** [comment]
This was resolved by https://github.com/vacuumlabs/name-bazaar/pull/40/commits/7b81b6bf56d2dc84e8b837dcaeff357de753e3d3#diff-34f7728a87fad737614971a560966821c28c2655e3de8e3869b8aa89b2896951

Feel free to reopen if you disagree.
